language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y mpd
script:
 - dotnet restore src
 - dotnet build src
 - dotnet test src/LibMpcTest/LibMpcTest.csproj
notifications:
 email:false
