name: Build and Test MpcNET

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: windows-latest  

    env:
      Solution_Name: MpcNET    
      Configuration: Release     

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore the application 
    - name: Restore the application
      working-directory: ./Sources
      run: |
        msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
        
    # Build package and upload to github packages
    - name: Build package
      working-directory: ./Sources
      run: |
        dotnet nuget add source --username Difegue --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Difegue/index.json"
        dotnet build $env:Solution_Name --configuration $env:Configuration
        dotnet pack --configuration $env:Configuration -o ./ 
        dotnet nuget push *.nupkg  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"

    # Execute all unit tests in the solution
    #- name: Execute unit tests
    #  working-directory: ./Sources
    #  run: dotnet test

